/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomasyonktp;

/**
 *
 * @author YAGMUR
 */
import javax.swing.table.DefaultTableModel;
import java.awt.Component;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.util.Date;

public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public static String yerD;
    public static int siraD;

    public AdminPanel() {
        initComponents();
        kitapListele();
        uyeListele();
        oduncListele();
        adminListele();
        borcKontrol();
        OduncKontrol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKitap = new javax.swing.JTable();
        btnKSil = new javax.swing.JButton();
        btnYeniK = new javax.swing.JButton();
        btnKDuzen = new javax.swing.JButton();
        txtKitA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUye = new javax.swing.JTable();
        txtUyeA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnUyeSil = new javax.swing.JButton();
        btnBorc = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOdunc = new javax.swing.JTable();
        OduncAra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnIadeOnay = new javax.swing.JButton();
        btnOduncSil = new javax.swing.JButton();
        yeniOdunc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();
        btnYeniAdmin = new javax.swing.JButton();
        btnAdminSil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnKapat = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Paneli");

        jTabbedPane1.setBackground(new java.awt.Color(238, 238, 238));

        tblKitap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKitap.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(tblKitap);

        btnKSil.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnKSil.setForeground(new java.awt.Color(204, 0, 0));
        btnKSil.setText("SİL");
        btnKSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKSilActionPerformed(evt);
            }
        });

        btnYeniK.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnYeniK.setForeground(new java.awt.Color(255, 0, 255));
        btnYeniK.setText("YENİ KİTAP");
        btnYeniK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniKActionPerformed(evt);
            }
        });

        btnKDuzen.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnKDuzen.setForeground(new java.awt.Color(204, 0, 204));
        btnKDuzen.setText("DÜZENLE");
        btnKDuzen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKDuzenActionPerformed(evt);
            }
        });

        txtKitA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKitAActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otomasyonktp/resimler/iconfinder_revisi_03_2191539.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnYeniK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKDuzen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKSil, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(txtKitA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtKitA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKDuzen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKSil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYeniK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kitaplar", jPanel2);

        tblUye.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUye.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tblUye.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tblUye);

        txtUyeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUyeAActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otomasyonktp/resimler/iconfinder_revisi_03_2191539.png"))); // NOI18N

        btnUyeSil.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnUyeSil.setForeground(new java.awt.Color(204, 0, 0));
        btnUyeSil.setText("SİL");
        btnUyeSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUyeSilActionPerformed(evt);
            }
        });

        btnBorc.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBorc.setForeground(new java.awt.Color(153, 51, 0));
        btnBorc.setText("Borç Ödendi");
        btnBorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(txtUyeA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBorc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUyeSil, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtUyeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUyeSil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Üyeler", jPanel3);

        tblOdunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOdunc.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(tblOdunc);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otomasyonktp/resimler/iconfinder_revisi_03_2191539.png"))); // NOI18N

        btnIadeOnay.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnIadeOnay.setForeground(new java.awt.Color(0, 102, 0));
        btnIadeOnay.setText("İADE EDİLDİ");
        btnIadeOnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIadeOnayActionPerformed(evt);
            }
        });

        btnOduncSil.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnOduncSil.setForeground(new java.awt.Color(204, 0, 0));
        btnOduncSil.setText("SİL");
        btnOduncSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduncSilActionPerformed(evt);
            }
        });

        yeniOdunc.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        yeniOdunc.setForeground(new java.awt.Color(153, 0, 153));
        yeniOdunc.setText("YENİ ÖDÜNÇ");
        yeniOdunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniOduncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(3, 3, 3)
                        .addComponent(OduncAra, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(yeniOdunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIadeOnay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOduncSil)
                        .addGap(31, 31, 31))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(OduncAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeniOdunc)
                    .addComponent(btnIadeOnay)
                    .addComponent(btnOduncSil))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ödünç İşlemleri", jPanel5);

        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblAdmin);

        btnYeniAdmin.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnYeniAdmin.setForeground(new java.awt.Color(0, 102, 102));
        btnYeniAdmin.setText("Yeni Ekle");
        btnYeniAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniAdminActionPerformed(evt);
            }
        });

        btnAdminSil.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnAdminSil.setForeground(new java.awt.Color(0, 204, 0));
        btnAdminSil.setText("SİL");
        btnAdminSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnYeniAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnAdminSil, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYeniAdmin)
                    .addComponent(btnAdminSil))
                .addGap(0, 89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin İşlemleri", jPanel1);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otomasyonktp/resimler/admin.png"))); // NOI18N
        jLabel2.setText("Admin Paneli");

        btnKapat.setBackground(new java.awt.Color(255, 0, 0));
        btnKapat.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnKapat.setForeground(new java.awt.Color(255, 255, 255));
        btnKapat.setText("Çıkış Yap");
        btnKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKapat)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKapat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKSilActionPerformed
        int sira = tblKitap.getSelectedRow();
        String yer = (String) tblKitap.getValueAt(sira, 5);
        try {
            if (yer != null) {
                Baglanti db = new Baglanti();
                ResultSet o = db.baglan().executeQuery("select odunc.kitapid from kitaplar inner join odunc on kitaplar.kitapid = odunc.kitapid where yer='" + yer + "'");

                if (o.next()) {
                    JOptionPane.showMessageDialog(rootPane, "Kitap Ödünç Olduğu için Silinemez!");
                } else {
                    db.baglan().executeUpdate("delete from kitaplar where yer='" + yer + "'");

                    JOptionPane.showMessageDialog(rootPane, "Kitap Silindi");
                    kitapListele();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Kitap Seçilmedi");
            }
        } catch (Exception e) {
            System.err.println("İşlem hatası:" + e);
        }
    }//GEN-LAST:event_btnKSilActionPerformed

    private void btnKDuzenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKDuzenActionPerformed
        siraD = tblKitap.getSelectedRow();
        yerD = (String) tblKitap.getValueAt(siraD, 5);
        try {
            if (yerD != null) {
                dispose();
                KitapDuzen k = new KitapDuzen();
                k.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Kitap Seçilmedi");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnKDuzenActionPerformed

    private void yeniOduncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniOduncActionPerformed
        // TODO add your handling code here:
        dispose();
        YeniOdunc yO = new YeniOdunc();
        yO.setVisible(true);
    }//GEN-LAST:event_yeniOduncActionPerformed

    private void btnYeniKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniKActionPerformed
        // TODO add your handling code here:
        YeniKitap yK = new YeniKitap();
        yK.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnYeniKActionPerformed

    private void btnKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKapatActionPerformed
        // TODO add your handling code here:
        AdminGiris a = new AdminGiris();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKapatActionPerformed

    private void txtKitAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKitAActionPerformed
        // TODO add your handling code here:
        KitapAra();
    }//GEN-LAST:event_txtKitAActionPerformed

    private void btnOduncSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduncSilActionPerformed
        // TODO add your handling code here:
        String oduncid = (String) tblOdunc.getValueAt(tblOdunc.getSelectedRow(), 1);
        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select * from odunc where oduncid='" + oduncid + "'");
            while (rs.next()) {
                if (rs.getString("iademi").equals("1")) {
                    JOptionPane.showMessageDialog(rootPane, "Bu işlem gerçekleştirilemez");
                } else {
                    db.baglan().executeUpdate("delete from odunc where oduncid='" + oduncid + "'");
                    oduncListele();
                }
            }
        } catch (Exception e) {
            System.err.println("İşlem hatası:" + e);
        }

    }//GEN-LAST:event_btnOduncSilActionPerformed

    private void btnIadeOnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIadeOnayActionPerformed
        // TODO add your handling code here:
        String odunc = (String) tblOdunc.getValueAt(tblOdunc.getSelectedRow(), 1);
        try {
            Baglanti db = new Baglanti();
            int o = Integer.parseInt(odunc);
            int od = db.baglan().executeUpdate("update odunc set iademi = 1, adminid = " + AdminGiris.adminID + " where kitapid = " + odunc + "");
            int od1 = db.baglan().executeUpdate("update kitaplar set raftami = 1 where kitapid = " + odunc);
            oduncListele();
            kitapListele();
        } catch (Exception e) {
            System.err.println("İşlem hatası:" + e);
        }
    }//GEN-LAST:event_btnIadeOnayActionPerformed

    private void txtUyeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUyeAActionPerformed
        // TODO add your handling code here:
        UyeAra();
    }//GEN-LAST:event_txtUyeAActionPerformed

    private void btnUyeSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUyeSilActionPerformed
        // TODO add your handling code here:
        int sira = tblUye.getSelectedRow();
        String ad = (String) tblUye.getValueAt(sira, 3);
        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select odunc.uyeid from uyeler inner join odunc on uyeler.uyeid = odunc.uyeid where uyeadi='" + ad + "'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(rootPane, "Ödünç kitaplar iade edilmeden üye silinemez!", null, JOptionPane.WARNING_MESSAGE);

            } else {
                int s = db.baglan().executeUpdate("delete from uyeler where uyeadi = '" + ad + "'");
                JOptionPane.showMessageDialog(rootPane, "Üye Silindi");
                uyeListele();
            }
        } catch (Exception e) {
            System.err.println("İşlem hatası:" + e);
        }
    }//GEN-LAST:event_btnUyeSilActionPerformed

    private void btnYeniAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniAdminActionPerformed
        // TODO add your handling code here:
        YeniAdmin yA = new YeniAdmin();
        yA.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnYeniAdminActionPerformed

    private void btnAdminSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSilActionPerformed
        // TODO add your handling code here:
        String admin = (String) tblAdmin.getValueAt(tblAdmin.getSelectedRow(), 2);
        try {
            if (admin != null) {
                Baglanti db = new Baglanti();

                db.baglan().executeUpdate("delete from admin where adminad='" + admin + "'");

                JOptionPane.showMessageDialog(rootPane, "Admin Silindi");
                if (Integer.parseInt(admin) == AdminGiris.adminID) {
                    AdminGiris A = new AdminGiris();
                    A.setVisible(true);
                    dispose();
                } else {
                    adminListele();
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Seçilmedi");
            }
        } catch (Exception e) {
            System.err.println("İşlem hatası:" + e);
        }
    }//GEN-LAST:event_btnAdminSilActionPerformed

    private void btnBorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorcActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog(null, "Emin misiniz? Bu işlem geri alınamaz.", "WARNING", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            int sira = tblUye.getSelectedRow();
            String ad = (String) tblUye.getValueAt(sira, 3);
            try {
                Baglanti db = new Baglanti();
                ResultSet rs = db.baglan().executeQuery("select * from uyeler where uyeadi='" + ad + "'");
                if (rs.next()) {
                    int s = db.baglan().executeUpdate("update uyeler set borcgun = 0 where uyeadi = '" + ad + "'");
                    uyeListele();
                }
            } catch (Exception e) {
                System.err.println("İşlem hatası:" + e);
            }
        } else {
            remove(dialogButton);
        }
    }//GEN-LAST:event_btnBorcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    void kitapListele() {
        int i = 0;
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Sıra No");
        dt.addColumn("Kitap Adı");
        dt.addColumn("Yazar Adı");
        dt.addColumn("Yayınevi");
        dt.addColumn("Basım Yılı");
        dt.addColumn("Yer");
        dt.addColumn("Durum");
        dt.addColumn("İşlem Yapan");

        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select * from kitaplar inner join admin on kitaplar.adminid = admin.adminid");

            while (rs.next()) {
                i += 1;
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy");
                String d = formatter.format(rs.getDate("BasimYili"));
                String raf = rs.getString("RaftaMi").equals("0") ? "Emanet" : "Rafta";
                dt.addRow(new String[]{Integer.toString(i), rs.getString("KitapAdi"), rs.getString("YazarAdi"),
                    rs.getString("YayinEvi"), d, rs.getString("Yer"), raf, rs.getString("adminbilgi")});

            }
            tblKitap.setModel(dt);
        } catch (Exception e) {
            System.err.println("İşlem hatası:" + e);
        }

    }

    void uyeListele() {
        int i = 0;
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Sıra No");
        dt.addColumn("Adı");
        dt.addColumn("Soyadı");
        dt.addColumn("Üye Adı");
        dt.addColumn("Mail");
        dt.addColumn("Sifre");
        dt.addColumn("Borç Durumu");
        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select * from uyeler");

            while (rs.next()) {
                i += 1;
                String borc = "";
                borc = rs.getString("borcgun") == null ? "Borç Yok" : rs.getString("borcgun") + " TL";

                dt.addRow(new String[]{Integer.toString(i), rs.getString("ad"), rs.getString("soyad"), rs.getString("uyeadi"), rs.getString("mail"), rs.getString("sifre"), borc});

            }
            tblUye.setModel(dt);
        } catch (Exception e) {
        }

    }

    void adminListele() {
        int i = 0;
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Sıra No");
        dt.addColumn("Ad Soyad");
        dt.addColumn("Admin Ad");
        dt.addColumn("Şifre");
        dt.addColumn("Mail");

        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select * from admin");

            while (rs.next()) {
                i += 1;
                dt.addRow(new String[]{Integer.toString(i), rs.getString("adminbilgi"), rs.getString("adminad"), rs.getString("adminsifre"), rs.getString("adminmail")});

            }
            tblAdmin.setModel(dt);
        } catch (Exception e) {
        }

    }

    void oduncListele() {
        int i = 0;
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Sıra No");
        dt.addColumn("Kitap ID");
        dt.addColumn("Kitap");
        dt.addColumn("Üye");
        dt.addColumn("Admin");
        dt.addColumn("Ödünç Tarihi");
        dt.addColumn("İade Tarihi");
        dt.addColumn("İade Durum");

        try {
            Baglanti db = new Baglanti();
            ResultSet rs2 = db.baglan().executeQuery("select kitaplar.kitapid, kitaplar.Kitapadi, uyeler.ad, uyeler.soyad, admin.adminBilgi, odunc.oduncTarih, odunc.iadeTarih, odunc.iadeMi "
                    + "from odunc "
                    + "inner join kitaplar on odunc.kitapID = kitaplar.kitapid "
                    + "inner join uyeler on odunc.uyeid = uyeler.uyeid "
                    + "inner join admin on odunc.adminid = admin.adminid");

            while (rs2.next()) {
                i += 1;
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                String oT = formatter.format(rs2.getDate("oduncTarih"));
                String iT = formatter.format(rs2.getDate("iadeTarih"));
                String odunc = rs2.getString("iadeMi").equals("0") ? "Ödünç" : "İade";
                dt.addRow(new String[]{Integer.toString(i), rs2.getString("kitapid"), rs2.getString("Kitapadi"), rs2.getString("ad") + " " + rs2.getString("soyad"), rs2.getString("adminbilgi"), oT, iT, odunc});

            }
            tblOdunc.setModel(dt);
        } catch (Exception e) {
        }

    }

    void KitapAra() {
        int i = 0;
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Sıra No");
        dt.addColumn("Kitap Adı");
        dt.addColumn("Yazar Adı");
        dt.addColumn("Yayınevi");
        dt.addColumn("Basım Yılı");
        dt.addColumn("Yer");
        dt.addColumn("Durum");
        String ara = txtKitA.getText();

        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select * from kitaplar where kitapadi like '%" + ara + "%' or yazaradi like '%" + ara + "%' or yayinevi like '%" + ara + "%'");

            while (rs.next()) {
                i += 1;
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy");
                String d = formatter.format(rs.getDate("BasimYili"));
                String raf = rs.getString("RaftaMi").equals("0") ? "Emanet" : "Rafta";
                dt.addRow(new String[]{Integer.toString(i), rs.getString("KitapAdi"), rs.getString("YazarAdi"),
                    rs.getString("YayinEvi"), d, rs.getString("Yer"), raf});
            }
            tblKitap.setModel(dt);
        } catch (Exception e) {
        }

    }

    void UyeAra() {
        int i = 0;
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Sıra No");
        dt.addColumn("Adı");
        dt.addColumn("Soyadı");
        dt.addColumn("Üye Adı");
        dt.addColumn("Mail");
        dt.addColumn("Sifre");
        String ara = txtUyeA.getText();

        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select * from uyeler where ad like '%" + ara + "%' or soyad like '%" + ara + "%' or uyeadi like '%" + ara + "%' or mail like '%" + ara + "%'");

            while (rs.next()) {
                i += 1;
                dt.addRow(new String[]{Integer.toString(i), rs.getString("ad"), rs.getString("soyad"), rs.getString("uyeadi"), rs.getString("mail"), rs.getString("sifre")});
            }
            tblUye.setModel(dt);
        } catch (Exception e) {
        }

    }

    void OduncKontrol() {
        String kitapad = "";
        String uyemail = "";
        try {
            Baglanti db = new Baglanti();
            ResultSet r = db.baglan().executeQuery("select * from odunc where iademi = 0");
            while (r.next()) {
                String iT = r.getString("iadeTarih");

                ResultSet rU = db.baglan().executeQuery("select * from uyeler where uyeid = " + r.getInt("uyeid"));
                while (rU.next()) {
                    uyemail = rU.getString("mail");
                }

                ResultSet rK = db.baglan().executeQuery("select * from kitaplar where kitapid = " + r.getInt("kitapid"));
                while (rK.next()) {
                    kitapad = rK.getString("kitapadi");
                }

                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Date d = formatter.parse(iT);
                Calendar c = Calendar.getInstance();
                c.setTime(d);
                Calendar a = Calendar.getInstance();
                a.add(Calendar.DATE, 1);
                Calendar b = Calendar.getInstance();
                b.add(Calendar.DATE, 3);
                String msg = "Almış olduğunuz " + kitapad + " isimli kitabın iade tarihi yaklaşmıştır. Lütfen iade tarihi geçmeden iade ediniz. Aksi takdirde borç yazılacaktır.";

                if (c.compareTo(a) == 1 && c.compareTo(b) == -1) {
                    MailAt.mailAt(uyemail, "Kitap iadesi hk.", msg);
                }

            }
        } catch (Exception e) {
            System.err.println("İşlem hatası:" + e);
        }
    }

    void borcKontrol() {
        int borcgun = 0;
        try {
            Baglanti db = new Baglanti();
            ResultSet r = db.baglan().executeQuery("select * from odunc where iademi = 0");
            while (r.next()) {
                String iT = r.getString("iadeTarih");
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Date d = formatter.parse(iT);
                Calendar c = Calendar.getInstance();
                c.setTime(d);
                Calendar now = Calendar.getInstance();
                int a = now.compareTo(c); //c gerideyse ve aynıysa 1, ilerideyse -1

                if (a == 1) {
                    c.add(Calendar.DATE, 1);
                    while (a == 1) {
                        borcgun += 1;
                        c.add(Calendar.DATE, 1);
                        a = now.compareTo(c);
                    }

                    db.baglan().executeUpdate("update uyeler set borcgun =" + borcgun + " where uyeid = '" + r.getString("uyeid") + "'");
                }

            }
        } catch (Exception e) {
            System.err.println("İşlem hatası:" + e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OduncAra;
    private javax.swing.JButton btnAdminSil;
    private javax.swing.JButton btnBorc;
    private javax.swing.JButton btnIadeOnay;
    private javax.swing.JButton btnKDuzen;
    private javax.swing.JButton btnKSil;
    private javax.swing.JButton btnKapat;
    private javax.swing.JButton btnOduncSil;
    private javax.swing.JButton btnUyeSil;
    private javax.swing.JButton btnYeniAdmin;
    private javax.swing.JButton btnYeniK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTable tblKitap;
    private javax.swing.JTable tblOdunc;
    private javax.swing.JTable tblUye;
    private javax.swing.JTextField txtKitA;
    private javax.swing.JTextField txtUyeA;
    private javax.swing.JButton yeniOdunc;
    // End of variables declaration//GEN-END:variables
}
