/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomasyonktp;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author YAGMUR
 */
public class SifreHatirlat extends javax.swing.JFrame {

    /**
     * Creates new form SifreHatirlat
     */
    public SifreHatirlat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMailAdres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sifre = new javax.swing.JLabel();
        lblUyeGir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Şifre Hatırlatma");

        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Mail Adresinizi Giriniz:");

        sifre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otomasyonktp/resimler/mailKey.png"))); // NOI18N
        sifre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifreMouseClicked(evt);
            }
        });

        lblUyeGir.setForeground(new java.awt.Color(102, 0, 0));
        lblUyeGir.setText("Üye Giriş");
        lblUyeGir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUyeGirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtMailAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sifre)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUyeGir)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMailAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sifre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(lblUyeGir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String adres;
    String konu;
    String mesaj;
    private void sifreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifreMouseClicked
        adres = txtMailAdres.getText();
        if (adres.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen boş bırakmayınız");
        } else {
            try {
                Baglanti db = new Baglanti();
                ResultSet rs = db.baglan().executeQuery("select * from uyeler where mail= '" + adres + "'");
                if (rs.next()) {
                    konu = "Üye Şifresi Hatırlatma";
                    mesaj = "Üye Şifreniz: " + rs.getString("Sifre");
                    MailAt.mailAt("yagmblr@gmail.com", konu, mesaj);
                    JOptionPane.showMessageDialog(rootPane, "Şifreniz mail adresinize gönderilmiştir. Lütfen kontrol ediniz.");

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bilgileri Kontrol Ediniz");
                }

            } catch (Exception e) {
                System.err.println("hata:" + e);
            }
        }
    }//GEN-LAST:event_sifreMouseClicked

    private void lblUyeGirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUyeGirMouseClicked
        GirisSayfa g = new GirisSayfa();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblUyeGirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SifreHatirlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SifreHatirlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SifreHatirlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SifreHatirlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SifreHatirlat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUyeGir;
    private javax.swing.JLabel sifre;
    private javax.swing.JTextField txtMailAdres;
    // End of variables declaration//GEN-END:variables
}
