/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomasyonktp;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author YAGMUR
 */
public class YeniUye extends javax.swing.JFrame {

    /**
     * Creates new form YeniUye
     */
    public YeniUye() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUyeAd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUyeSoyad = new javax.swing.JTextField();
        txtUyeSifre = new javax.swing.JPasswordField();
        txtUyeMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUyeUye = new javax.swing.JTextField();
        btnYKOnay = new javax.swing.JButton();
        lblUye = new javax.swing.JLabel();
        lblAd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yeni Üye Kaydı");

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel4.setText("Mail");

        jLabel5.setText("Şifre");

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("YENİ ÜYE KAYDI");

        jLabel3.setText("Üye Adı");

        txtUyeUye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUyeUyeActionPerformed(evt);
            }
        });
        txtUyeUye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUyeUyeKeyReleased(evt);
            }
        });

        btnYKOnay.setText("Kayıt Ol");
        btnYKOnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYKOnayActionPerformed(evt);
            }
        });

        lblUye.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblUye.setForeground(new java.awt.Color(153, 0, 0));
        lblUye.setText("Üye Girişi");
        lblUye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUyeMouseClicked(evt);
            }
        });

        lblAd.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblAd.setForeground(new java.awt.Color(255, 0, 0));
        lblAd.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUyeMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(txtUyeSoyad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUyeUye, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUyeAd)
                                    .addComponent(txtUyeSifre))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnYKOnay)
                        .addGap(103, 103, 103))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUye)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUyeAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUyeSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUyeUye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblAd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUyeMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUyeSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnYKOnay)
                .addGap(26, 26, 26)
                .addComponent(lblUye)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYKOnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYKOnayActionPerformed
        // TODO add your handling code here:
        String ad = txtUyeAd.getText();
        String soyad = txtUyeSoyad.getText();
        String mail = txtUyeMail.getText();
        String uyead = txtUyeUye.getText();
        String sifre = new String(txtUyeSifre.getPassword());

        if (ad.equals("") || soyad.equals("") || mail.equals("") || uyead.equals("") || sifre.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen boş bırakmayınız");
        } else {
            try {
                Baglanti db = new Baglanti();
                boolean s = db.baglan().execute("select * from uyeler where uyeadi ='"+uyead+"'");
               if(s)
                     JOptionPane.showMessageDialog(rootPane, "Bu üye adıyla üye olamazsınız!");
               else{
                int rs = db.baglan().executeUpdate("insert into uyeler(ad, soyad, uyeadi, mail, sifre, borcgun)"
                        + " values('" + ad + "','" + soyad + "','" + uyead + "','" + mail + "','" + sifre + "', 0)");
                if (rs>0) {
                    JOptionPane.showMessageDialog(rootPane, "Üye Olma başarılı");
                    dispose();

                    GirisSayfa g = new GirisSayfa();
                    g.setVisible(true);
                }
               }
            } catch (Exception e) {
                System.err.println("İşlem hatası:" + e);
            }

        }
    }//GEN-LAST:event_btnYKOnayActionPerformed

    private void lblUyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUyeMouseClicked
        // TODO add your handling code here:
        GirisSayfa g = new GirisSayfa();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblUyeMouseClicked

    private void txtUyeUyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUyeUyeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUyeUyeActionPerformed

    private void txtUyeUyeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUyeUyeKeyReleased
        // TODO add your handling code here:
        UyeKontrol();
    }//GEN-LAST:event_txtUyeUyeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YeniUye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YeniUye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YeniUye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YeniUye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YeniUye().setVisible(true);
            }
        });
    }

    void UyeKontrol()
    {
         String uye = txtUyeUye.getText();
         try {
                Baglanti db = new Baglanti();
                ResultSet rs = db.baglan().executeQuery("select * from uyeler where uyeadi = '"+ uye + "'");
                while(rs.next()) {
                  lblAd.setText("!");
                }

            } catch (Exception e) {
                System.err.println("İşlem hatası:" + e);
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnYKOnay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblUye;
    private javax.swing.JTextField txtUyeAd;
    private javax.swing.JTextField txtUyeMail;
    private javax.swing.JPasswordField txtUyeSifre;
    private javax.swing.JTextField txtUyeSoyad;
    private javax.swing.JTextField txtUyeUye;
    // End of variables declaration//GEN-END:variables
}
