/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomasyonktp;

import java.sql.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author YAGMUR
 */
public class YeniOdunc extends javax.swing.JFrame {

    /**
     * Creates new form YeniOdunc
     */
    public YeniOdunc() {
        initComponents();
        uyeCombo();
        kitapCombo();
        Calendar c = Calendar.getInstance();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String odunc = f.format(c.getTime());
        lblOdunc.setText(odunc);
        c.add(Calendar.DATE, 14);
        String iade = f.format(c.getTime());
        lblIade.setText(iade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbUyeAd = new javax.swing.JComboBox();
        cmbKitap = new javax.swing.JComboBox();
        btnOduncOnay = new javax.swing.JButton();
        lblAdminPanel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblOdunc = new javax.swing.JLabel();
        lblIade = new javax.swing.JLabel();
        cmbUyeSoyad = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbYazar = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yeni Ödünç");

        jLabel1.setText("Ad");

        jLabel2.setText("Kitap");

        jLabel3.setText("Ödünç Tarihi");

        cmbUyeAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUyeAdActionPerformed(evt);
            }
        });

        cmbKitap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKitapActionPerformed(evt);
            }
        });

        btnOduncOnay.setText("Onayla");
        btnOduncOnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduncOnayActionPerformed(evt);
            }
        });

        lblAdminPanel.setForeground(new java.awt.Color(153, 0, 0));
        lblAdminPanel.setText("Admin Paneli");
        lblAdminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminPanelMouseClicked(evt);
            }
        });

        jLabel5.setText("İade Tarihi");

        lblOdunc.setText("-");

        lblIade.setText("-");

        jLabel6.setText("Soyad");

        jLabel7.setText("Yazar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAdminPanel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOduncOnay)
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOdunc)
                            .addComponent(lblIade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUyeSoyad, 0, 97, Short.MAX_VALUE)
                            .addComponent(cmbYazar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKitap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUyeAd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUyeAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUyeSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbKitap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbYazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblOdunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblIade))
                .addGap(7, 7, 7)
                .addComponent(btnOduncOnay)
                .addGap(5, 5, 5)
                .addComponent(lblAdminPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAdminPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminPanelMouseClicked
        // TODO add your handling code here:
        AdminPanel aP = new AdminPanel();
        aP.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAdminPanelMouseClicked

    private void btnOduncOnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduncOnayActionPerformed
        // TODO add your handling code here:
        String kitap = cmbKitap.getSelectedItem().toString();
        String yazar = cmbYazar.getSelectedItem().toString();
        String uyead= cmbUyeAd.getSelectedItem().toString();
        String soyad = cmbUyeSoyad.getSelectedItem().toString();
        String oduncT = lblOdunc.getText();
        String iadeT = lblIade.getText();
        String K ="", U ="";
        
        if (kitap.equals("") || yazar.equals("") || uyead.equals("") || soyad.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen boş bırakmayınız");
        } else {
            try {
                Baglanti db = new Baglanti();
                ResultSet rsK = db.baglan().executeQuery("select kitapid from kitaplar where kitapadi = '"+kitap+"' and yazaradi = '"+yazar+"'");
                ResultSet rsU = db.baglan().executeQuery("select uyeid from uyeler where ad = '"+uyead+"' and soyad ='"+soyad+"'");
               
                if(rsK.next())
                 K = rsK.getString("kitapid");
               
                if(rsU.next())
                   U =rsU.getString("uyeid");
                
                int ek = db.baglan().executeUpdate("insert into odunc(kitapid, uyeid, adminid, odunctarih, iadetarih, iademi)"
                    + " values('" + K + "', '" + U + "', '" + AdminGiris.adminID +"', '"+ oduncT + "','"+iadeT+"','0')");
              db.baglan().executeUpdate("update kitaplar set raftami = 0, adminid = "+ AdminGiris.adminID+" where kitapid = "+ K);
                if (ek == 1) {
                    JOptionPane.showMessageDialog(rootPane, "İşlem Onaylandı");
                   
                }

            } catch (Exception e) {
                System.err.println("İşlem hatası:" + e);
            }
        }
    }//GEN-LAST:event_btnOduncOnayActionPerformed

    private void cmbUyeAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUyeAdActionPerformed
        // TODO add your handling code here:
        uyeSCombo();
    }//GEN-LAST:event_cmbUyeAdActionPerformed

    private void cmbKitapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKitapActionPerformed
        // TODO add your handling code here:
         yazarCombo();
    }//GEN-LAST:event_cmbKitapActionPerformed

    void uyeCombo() {
        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select ad from uyeler");
            while (rs.next()) {
                cmbUyeAd.addItem(rs.getString("ad"));
            }
        } catch (Exception e) {
        }

    }
     void uyeSCombo() {
          cmbUyeSoyad.removeAllItems();
        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select soyad from uyeler where ad = '" +cmbUyeAd.getSelectedItem().toString()+"'");
            while (rs.next()) {
                cmbUyeSoyad.addItem(rs.getString("soyad"));
            }
        } catch (Exception e) {
        }

    }

    void kitapCombo() {
        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select kitapadi from kitaplar where raftami = 1");
            while (rs.next()) {
                cmbKitap.addItem(rs.getString("kitapadi"));
            }
        } catch (Exception e) {
        }

    }
    void yazarCombo() {
        cmbYazar.removeAllItems();
        try {
            Baglanti db = new Baglanti();
            ResultSet rs = db.baglan().executeQuery("select yazaradi from kitaplar where kitapadi = '"+cmbKitap.getSelectedItem().toString()+"'");
            while (rs.next()) {
                cmbYazar.addItem(rs.getString("yazaradi"));
            }
        } catch (Exception e) {
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YeniOdunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YeniOdunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YeniOdunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YeniOdunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YeniOdunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOduncOnay;
    private javax.swing.JComboBox cmbKitap;
    private javax.swing.JComboBox cmbUyeAd;
    private javax.swing.JComboBox cmbUyeSoyad;
    private javax.swing.JComboBox cmbYazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAdminPanel;
    private javax.swing.JLabel lblIade;
    private javax.swing.JLabel lblOdunc;
    // End of variables declaration//GEN-END:variables
}
