/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomasyonktp;

import javax.swing.JOptionPane;

/**
 *
 * @author YAGMUR
 */
public class YeniAdmin extends javax.swing.JFrame {

    String mail ="";
    /**
     * Creates new form YeniAdmin
     */
    public YeniAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdminKayit = new javax.swing.JButton();
        txtAdminBilgi = new javax.swing.JTextField();
        txtAdminAd = new javax.swing.JTextField();
        lblAdminMail = new javax.swing.JLabel();
        pswAdmin = new javax.swing.JPasswordField();
        lblAPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ad Soyad");

        jLabel2.setText("Admin Ad");

        jLabel3.setText("Şifre");

        jLabel4.setText("Admin Mail");

        btnAdminKayit.setText("Kaydet");
        btnAdminKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminKayitActionPerformed(evt);
            }
        });

        txtAdminAd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdminAdKeyTyped(evt);
            }
        });

        lblAdminMail.setText("-");

        lblAPanel.setForeground(new java.awt.Color(102, 0, 0));
        lblAPanel.setText("AdminPanel");
        lblAPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanel(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminAd, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(txtAdminBilgi)
                            .addComponent(lblAdminMail)
                            .addComponent(pswAdmin))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAPanel)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(btnAdminKayit)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAdminBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAdminAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pswAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAdminMail))
                .addGap(8, 8, 8)
                .addComponent(btnAdminKayit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblAPanel)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminKayitActionPerformed
        // TODO add your handling code here:
        String bilgi = txtAdminBilgi.getText();
        String admin = txtAdminAd.getText();
        String sifre = new String(pswAdmin.getPassword());

        if (bilgi.equals("") || admin.equals("") || sifre.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen boş bırakmayınız");
        } else {
            try {
                Baglanti db = new Baglanti();
                int ek = db.baglan().executeUpdate("insert into admin(adminbilgi, adminad, adminsifre, adminmail)"
                    + " values('" + bilgi + "','" + admin + "','" + sifre + "','" + mail + "')");
                if (ek > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Admin Kaydedildi");
                          AdminPanel aP = new AdminPanel();
        aP.setVisible(true);
        dispose();
                }

            } catch (Exception e) {
                System.err.println("İşlem hatası:" + e);
            }
        }
    }//GEN-LAST:event_btnAdminKayitActionPerformed

    private void adminPanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanel
        // TODO add your handling code here:
                AdminPanel aP = new AdminPanel();
        aP.setVisible(true);
        dispose();
    }//GEN-LAST:event_adminPanel

    private void txtAdminAdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminAdKeyTyped
        // TODO add your handling code here:
        mail = txtAdminAd.getText()+"@kitap.com";
        lblAdminMail.setText(mail);
    }//GEN-LAST:event_txtAdminAdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YeniAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YeniAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YeniAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YeniAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YeniAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminKayit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAPanel;
    private javax.swing.JLabel lblAdminMail;
    private javax.swing.JPasswordField pswAdmin;
    private javax.swing.JTextField txtAdminAd;
    private javax.swing.JTextField txtAdminBilgi;
    // End of variables declaration//GEN-END:variables
}
